version: '3.6'

volumes:
  db:
  app-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./invoiceninja

# uncomment if you want to use external network (example network: "web")
#networks:
#  web:
#    external: true

services:
  db:
    image: mysql:5
    env_file: ./config/.env
    #restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - default

  app:
    image: invoiceninja:dev
    build:
      context: .
      dockerfile: Dockerfile.invoiceninja
    env_file: ./config/.env
    #restart: always
    depends_on:
      - db
    volumes:
      -  app-data:/var/www/app
    networks: 
      - default  

  web:
    image: nginx:1
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      -  app-data:/var/www/app
    expose: # Expose ports without publishing them to the host machine - they’ll only be accessible to linked services.
      - "80"
    depends_on:
      - app
    ports: # Delete if you want to use reverse proxy
      - 8000:80
    networks:
#      - web        # uncomment if you want to use  external network (reverse proxy for example)
      - default

  cron:
    image: invoiceninja:dev
    build:
      context: .
      dockerfile: Dockerfile.invoiceninja
    env_file: ./config/.env
    volumes:
      -  app-data:/var/www/app
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 300s
      while /bin/true; do
        ./artisan ninja:send-invoices
        ./artisan ninja:send-reminders
        sleep 1d
      done
      EOF'
    networks:
      - default
