version: '3'

volumes:
  db:

networks:
  main:

# uncomment if you want to use external network (example network: "web")
#networks:
#  web:
#    external: true

services:
  db:
    image: mysql:5
    env_file: ./config/.env
    #restart: always
    volumes:
      - db:/var/lib/mysql
    networks: 
      main:
        aliases: 
          - db  

  app:
    image: invoiceninja:dev
    build:
      context: .
      dockerfile: Dockerfile.invoiceninja
    env_file: ./config/.env
    #restart: always
    depends_on:
      - db
    volumes:
      -  ./invoiceninja:/var/www/app
    networks: 
      main:
        aliases: 
          - app  

  web:
    image: nginx:1
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./invoiceninja:/var/www/app
    expose: # Expose ports without publishing them to the host machine - they’ll only be accessible to linked services.
      - "80"
    depends_on:
      - app
    ports: # Delete if you want to use reverse proxy
      - 8000:80
    networks: 
      main:
        aliases: 
          - web  

  cron:
    image: invoiceninja:dev
    build:
      context: .
      dockerfile: Dockerfile.invoiceninja
    env_file: ./config/.env
    volumes:
      - ./invoiceninja:/var/www/app
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 300s
      while /bin/true; do
        ./artisan ninja:send-invoices
        ./artisan ninja:send-reminders
        sleep 1d
      done
      EOF'
    networks: 
      main:
        aliases: 
          - cron